### ISSUE TITLE
Completing the Hyperconductive HW step for a job removes materials from the "Count" section on the Anima tab and adds to the "Remaining" section.

### ISSUE THREAD

**Issue by Hezkezl** [VarsityPhysicist/FFXIVRelicTracker#10]
I have PLD and BLM completely done for HW relics, and I have WAR and DRK marked as having completed the Hyperconductive steps. So right now the Anima tab shows that I need 90 Unidentifiable items and 36 Crafted items (Kingcake, Dispelling Arrow, etc) for my remaining jobs. All jobs have the Animated step done, but no others have anything else completed (pictured like so:) 
![image](https://user-images.githubusercontent.com/15794090/112554614-40fa1080-8d8c-11eb-8647-aa788f6e0f8e.png)

If I go to the Anima tab and change the Count in both of the columns to 90 and 36, so that "Remaining" is set to 0 (like this picture:) ![image](https://cdn.discordapp.com/attachments/151525074644631553/824781107948945459/unknown.png) and then I select an Active Job (White Mage) and mark it as completed, it properly reduces the number of items (to 80 and 32 items respectively). The "Remaining" column for those stays at 0. (Picture here:) ![image](https://cdn.discordapp.com/attachments/151525074644631553/824781473025622046/unknown.png)

However, if I then move on to the Hyperconductive step, and select the same job (WHM) as the Active job and then "Mark as completed", when I go back to the Anima tab I now show a "70" or "28" in the "Count" columns, and now magically there is a "10" and a "4" in the "Remaining" columns. ![image](https://cdn.discordapp.com/attachments/151525074644631553/824781724696969236/unknown.png)

So somehow, completing the Aether Oil step for this is removing items from the Count section and adding them to the Remaining section for whatever reason...guessing there's some screwy math typo going on behind the scenes somewhere D: Because completing the Hyperconductive/Aether Oil step shouldn't have any effect at all on any other tab.

**Comment by VarsityPhysicist** [comment]
Thank you for letting me know about this!

I just published a fix for this - the issue was that when completing a stage, all prior stages are completed as well and the stage completion process adjusts the materials, I added a check to see if the prior stage is completed before doing this and that appears to have resolved the issue
