### ISSUE TITLE
Not working, Install .net core

### ISSUE THREAD

**Issue by Kumicoo** [VarsityPhysicist/FFXIVRelicTracker#4]
Keeps telling me to install .net Core.

I have .net Core, even reinstalled & repaired

Other .net core applications work.

**Comment by VarsityPhysicist** [comment]
Can you open the command prompt, enter 
dotnet --info
and post that here?

**Comment by VarsityPhysicist** [comment]
I've made a test release here https://github.com/VarsityPhysicist/FFXIVRelicTracker/releases/tag/v1.7p that may resolve the issue

What OS arm you on?

**Comment by VarsityPhysicist** [comment]
I've gotten reports from other users that the portable release has resolved this issue for them and I will mark this as closed.

Thank you for reporting this issue, If this is not resolved or you have any other bugs/issues, feel free to open new items
