### ISSUE TITLE
[BUG] Pneumite value not saving/always appears as 0 when reloading

### ISSUE THREAD

**Issue by Hezkezl** [VarsityPhysicist/FFXIVRelicTracker#8]
In the "HW View" -> Complete section, if you enter in a value for Pneumite (say 90), then go back to the Main Menu and save it, close the program and re-open it, hit load, then load up your character and go back to the HW/Complete menu...the Pneumite will have reset back to 0. So it doesn't appear to be saving the value for some reason.

Everything else in other menus saves (Singing Clusters, Umbrite, Crystal Sand, Unidentified Items, etc) it's just Pneumite which doesn't.

EDIT: Also, found one small typo. HW View -> Awoken. The "Complete  Sashtasha (Hard)" has a double space after 'Complete' and before 'Sashtasha', in addition to the name of the dungeon being misspelled. It should be "Sastasha (Hard)"  (only one h!)

**Comment by VarsityPhysicist** [comment]
Thank you!
I fixed the saving/loading in the most recent release

I came here to reply and noticed the typo error, I fixed that but it will be included in the next version
